// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfoexdoonxmojxunailz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmb2V4ZG9vbnhtb2p4dW5haWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDA1NTYsImV4cCI6MjA2NTgxNjU1Nn0.ytwRft3qlosISMLnDyF20g8MqpgRPTzfzM8Xyn_D7SQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});